/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import {
    RigidBody,
    CuboidCollider,
    CollisionPayload,
} from "@react-three/rapier";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh;
    };
    materials: {
        Material: THREE.MeshStandardMaterial;
    };
};

export function Goal({
    setScore,
    player,
    position,
    rotation,
}: Readonly<{
    setScore: React.Dispatch<React.SetStateAction<{ p1: number; p2: number }>>;
    position?: [number, number, number];
    rotation?: [number, number, number];
    player: "p1" | "p2";
}>) {
    const { nodes, materials } = useGLTF("/goal.glb") as GLTFResult;
    const rinkDimensions = new THREE.Vector3(1.863, 1, 0.681);
    const colliderDimensions = rinkDimensions.clone().multiplyScalar(0.9);

    const handleIntersectionEnter = (e: CollisionPayload) => {
        const parent = e.colliderObject?.parent;

        if (!parent) {
            return;
        }

        const userData = parent.userData as { type: string };

        if (userData.type === "puck") {
            setScore((prev: { p1: number; p2: number }) => ({
                ...prev,
                [player]: prev[player] + 1,
            }));
        }
    };

    return (
        <RigidBody type="fixed" colliders="trimesh">
            <group dispose={null} position={position} rotation={rotation}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={materials.Material}
                    material-transparent
                    material-opacity={0.5}
                    position={[0, 1, 0]}
                    scale={rinkDimensions}
                />
                <CuboidCollider
                    args={[
                        colliderDimensions.x,
                        colliderDimensions.y,
                        colliderDimensions.z,
                    ]}
                    onIntersectionEnter={handleIntersectionEnter}
                    sensor
                />
            </group>
        </RigidBody>
    );
}

useGLTF.preload("/goal.glb");
