/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Icosphere252: THREE.Mesh;
    Icosphere253: THREE.Mesh;
    Icosphere254: THREE.Mesh;
    Icosphere255: THREE.Mesh;
    Icosphere256: THREE.Mesh;
    Icosphere257: THREE.Mesh;
    Icosphere258: THREE.Mesh;
    Icosphere259: THREE.Mesh;
    Icosphere260: THREE.Mesh;
    Icosphere261: THREE.Mesh;
    Icosphere262: THREE.Mesh;
    Icosphere263: THREE.Mesh;
    Icosphere264: THREE.Mesh;
    Icosphere265: THREE.Mesh;
    Icosphere266: THREE.Mesh;
    Icosphere267: THREE.Mesh;
    Icosphere268: THREE.Mesh;
    Icosphere269: THREE.Mesh;
    Icosphere270: THREE.Mesh;
    Icosphere271: THREE.Mesh;
    Icosphere272: THREE.Mesh;
    Icosphere273: THREE.Mesh;
    Icosphere274: THREE.Mesh;
    Icosphere275: THREE.Mesh;
    Icosphere276: THREE.Mesh;
    Icosphere277: THREE.Mesh;
    Icosphere278: THREE.Mesh;
    Icosphere279: THREE.Mesh;
    Icosphere280: THREE.Mesh;
    Icosphere281: THREE.Mesh;
    Icosphere282: THREE.Mesh;
    Icosphere283: THREE.Mesh;
    Icosphere284: THREE.Mesh;
    Icosphere285: THREE.Mesh;
    Icosphere286: THREE.Mesh;
    Icosphere287: THREE.Mesh;
    Icosphere288: THREE.Mesh;
    Icosphere289: THREE.Mesh;
    Icosphere290: THREE.Mesh;
    Icosphere291: THREE.Mesh;
    Icosphere292: THREE.Mesh;
    Icosphere293: THREE.Mesh;
    Icosphere294: THREE.Mesh;
    Icosphere295: THREE.Mesh;
    Icosphere296: THREE.Mesh;
    Icosphere297: THREE.Mesh;
    Icosphere298: THREE.Mesh;
    Icosphere299: THREE.Mesh;
    Icosphere300: THREE.Mesh;
    Icosphere301: THREE.Mesh;
    Icosphere302: THREE.Mesh;
    Icosphere303: THREE.Mesh;
    Icosphere304: THREE.Mesh;
    Icosphere305: THREE.Mesh;
    Icosphere306: THREE.Mesh;
    Icosphere307: THREE.Mesh;
    Icosphere308: THREE.Mesh;
    Icosphere309: THREE.Mesh;
    Icosphere310: THREE.Mesh;
    Icosphere311: THREE.Mesh;
    Icosphere312: THREE.Mesh;
    Icosphere313: THREE.Mesh;
    Icosphere314: THREE.Mesh;
    Icosphere315: THREE.Mesh;
    Icosphere316: THREE.Mesh;
    Icosphere317: THREE.Mesh;
    Icosphere318: THREE.Mesh;
    Icosphere319: THREE.Mesh;
    Icosphere320: THREE.Mesh;
    Icosphere321: THREE.Mesh;
    Icosphere322: THREE.Mesh;
    Icosphere323: THREE.Mesh;
    Cube1051: THREE.Mesh;
    Cube1051_1: THREE.Mesh;
    Icosphere324: THREE.Mesh;
    Icosphere325: THREE.Mesh;
    Icosphere326: THREE.Mesh;
    Icosphere327: THREE.Mesh;
    Icosphere328: THREE.Mesh;
    Icosphere329: THREE.Mesh;
    Icosphere330: THREE.Mesh;
    Icosphere331: THREE.Mesh;
    Icosphere332: THREE.Mesh;
    Icosphere333: THREE.Mesh;
    Icosphere334: THREE.Mesh;
    Icosphere335: THREE.Mesh;
    Icosphere336: THREE.Mesh;
    Icosphere337: THREE.Mesh;
    Icosphere338: THREE.Mesh;
    Icosphere339: THREE.Mesh;
    Icosphere340: THREE.Mesh;
    Icosphere341: THREE.Mesh;
    Icosphere342: THREE.Mesh;
    Icosphere343: THREE.Mesh;
    Icosphere344: THREE.Mesh;
    Icosphere345: THREE.Mesh;
    Icosphere346: THREE.Mesh;
    Icosphere347: THREE.Mesh;
    Icosphere348: THREE.Mesh;
    Icosphere349: THREE.Mesh;
    Icosphere350: THREE.Mesh;
    Icosphere351: THREE.Mesh;
    Icosphere352: THREE.Mesh;
    Icosphere353: THREE.Mesh;
    Icosphere354: THREE.Mesh;
    Icosphere355: THREE.Mesh;
    Icosphere356: THREE.Mesh;
    Icosphere357: THREE.Mesh;
    Icosphere358: THREE.Mesh;
    Icosphere359: THREE.Mesh;
    Cube1052: THREE.Mesh;
    Cube1052_1: THREE.Mesh;
    Icosphere360: THREE.Mesh;
    Icosphere361: THREE.Mesh;
    Icosphere362: THREE.Mesh;
    Icosphere363: THREE.Mesh;
    Icosphere364: THREE.Mesh;
    Icosphere365: THREE.Mesh;
    Icosphere366: THREE.Mesh;
    Icosphere367: THREE.Mesh;
    Icosphere368: THREE.Mesh;
    Icosphere369: THREE.Mesh;
    Icosphere370: THREE.Mesh;
    Icosphere371: THREE.Mesh;
    Icosphere372: THREE.Mesh;
    Icosphere373: THREE.Mesh;
    Icosphere374: THREE.Mesh;
    Icosphere375: THREE.Mesh;
    Icosphere376: THREE.Mesh;
    Icosphere377: THREE.Mesh;
    Icosphere378: THREE.Mesh;
    Icosphere379: THREE.Mesh;
    Icosphere380: THREE.Mesh;
    Icosphere381: THREE.Mesh;
    Icosphere382: THREE.Mesh;
    Icosphere383: THREE.Mesh;
    Icosphere384: THREE.Mesh;
    Icosphere385: THREE.Mesh;
    Icosphere386: THREE.Mesh;
    Icosphere387: THREE.Mesh;
    Icosphere388: THREE.Mesh;
    Icosphere389: THREE.Mesh;
    Icosphere390: THREE.Mesh;
    Icosphere391: THREE.Mesh;
    Icosphere392: THREE.Mesh;
    Icosphere393: THREE.Mesh;
    Icosphere394: THREE.Mesh;
    Icosphere395: THREE.Mesh;
    Cube608: THREE.Mesh;
    Cube608_1: THREE.Mesh;
    Cube700: THREE.Mesh;
    Cube700_1: THREE.Mesh;
  };
  materials: {
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
  };
};

export function Trees(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/trees.glb") as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Icosphere252"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere252.geometry}
          material={materials["Material.006"]}
          position={[12.216, 2.008, -17.295]}
        />
        <mesh
          name="Icosphere253"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere253.geometry}
          material={materials["Material.006"]}
          position={[12.21, 2.049, -16.047]}
        />
        <mesh
          name="Icosphere254"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere254.geometry}
          material={materials["Material.006"]}
          position={[12.298, 1.911, -14.811]}
        />
        <mesh
          name="Icosphere255"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere255.geometry}
          material={materials["Material.006"]}
          position={[12.627, 2.904, -15.543]}
        />
        <mesh
          name="Icosphere256"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere256.geometry}
          material={materials["Material.006"]}
          position={[12.627, 3.01, -16.725]}
        />
        <mesh
          name="Icosphere257"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere257.geometry}
          material={materials["Material.006"]}
          position={[12.946, 3.896, -16.592]}
        />
        <mesh
          name="Icosphere258"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere258.geometry}
          material={materials["Material.006"]}
          position={[12.946, 4.038, -15.725]}
        />
        <mesh
          name="Icosphere259"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere259.geometry}
          material={materials["Material.006"]}
          position={[13.177, 4.998, -15.808]}
        />
        <mesh
          name="Icosphere260"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere260.geometry}
          material={materials["Material.006"]}
          position={[13.483, 5.962, -16.076]}
        />
        <mesh
          name="Icosphere261"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere261.geometry}
          material={materials["Material.006"]}
          position={[15.812, 2.008, -14.843]}
        />
        <mesh
          name="Icosphere262"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere262.geometry}
          material={materials["Material.006"]}
          position={[15.817, 2.049, -16.091]}
        />
        <mesh
          name="Icosphere263"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere263.geometry}
          material={materials["Material.006"]}
          position={[15.73, 1.911, -17.327]}
        />
        <mesh
          name="Icosphere264"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere264.geometry}
          material={materials["Material.006"]}
          position={[15.4, 2.904, -16.595]}
        />
        <mesh
          name="Icosphere265"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere265.geometry}
          material={materials["Material.006"]}
          position={[15.4, 3.01, -15.413]}
        />
        <mesh
          name="Icosphere266"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere266.geometry}
          material={materials["Material.006"]}
          position={[15.081, 3.896, -15.546]}
        />
        <mesh
          name="Icosphere267"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere267.geometry}
          material={materials["Material.006"]}
          position={[15.081, 4.038, -16.413]}
        />
        <mesh
          name="Icosphere268"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere268.geometry}
          material={materials["Material.006"]}
          position={[14.85, 4.998, -16.33]}
        />
        <mesh
          name="Icosphere269"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere269.geometry}
          material={materials["Material.006"]}
          position={[14.545, 5.962, -16.062]}
        />
        <mesh
          name="Icosphere270"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere270.geometry}
          material={materials["Material.006"]}
          position={[12.787, 2.008, -14.271]}
        />
        <mesh
          name="Icosphere271"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere271.geometry}
          material={materials["Material.006"]}
          position={[14.036, 2.049, -14.266]}
        />
        <mesh
          name="Icosphere272"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere272.geometry}
          material={materials["Material.006"]}
          position={[15.272, 1.911, -14.353]}
        />
        <mesh
          name="Icosphere273"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere273.geometry}
          material={materials["Material.006"]}
          position={[14.54, 2.904, -14.683]}
        />
        <mesh
          name="Icosphere274"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere274.geometry}
          material={materials["Material.006"]}
          position={[13.358, 3.01, -14.683]}
        />
        <mesh
          name="Icosphere275"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere275.geometry}
          material={materials["Material.006"]}
          position={[13.491, 3.896, -15.002]}
        />
        <mesh
          name="Icosphere276"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere276.geometry}
          material={materials["Material.006"]}
          position={[14.358, 4.038, -15.002]}
        />
        <mesh
          name="Icosphere277"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere277.geometry}
          material={materials["Material.006"]}
          position={[14.275, 4.998, -15.233]}
        />
        <mesh
          name="Icosphere278"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere278.geometry}
          material={materials["Material.006"]}
          position={[14.007, 5.962, -15.538]}
        />
        <mesh
          name="Icosphere279"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere279.geometry}
          material={materials["Material.006"]}
          position={[15.24, 2.008, -17.867]}
        />
        <mesh
          name="Icosphere280"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere280.geometry}
          material={materials["Material.006"]}
          position={[13.991, 2.049, -17.873]}
        />
        <mesh
          name="Icosphere281"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere281.geometry}
          material={materials["Material.006"]}
          position={[12.755, 1.911, -17.785]}
        />
        <mesh
          name="Icosphere282"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere282.geometry}
          material={materials["Material.006"]}
          position={[13.487, 2.904, -17.456]}
        />
        <mesh
          name="Icosphere283"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere283.geometry}
          material={materials["Material.006"]}
          position={[14.669, 3.01, -17.456]}
        />
        <mesh
          name="Icosphere284"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere284.geometry}
          material={materials["Material.006"]}
          position={[14.536, 3.896, -17.136]}
        />
        <mesh
          name="Icosphere285"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere285.geometry}
          material={materials["Material.006"]}
          position={[13.67, 4.038, -17.136]}
        />
        <mesh
          name="Icosphere286"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere286.geometry}
          material={materials["Material.006"]}
          position={[13.753, 4.998, -16.905]}
        />
        <mesh
          name="Icosphere287"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere287.geometry}
          material={materials["Material.006"]}
          position={[14.02, 5.962, -16.6]}
        />
        <mesh
          name="Icosphere288"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere288.geometry}
          material={materials["Material.006"]}
          position={[-15.784, 2.008, -17.295]}
        />
        <mesh
          name="Icosphere289"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere289.geometry}
          material={materials["Material.006"]}
          position={[-15.79, 2.049, -16.047]}
        />
        <mesh
          name="Icosphere290"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere290.geometry}
          material={materials["Material.006"]}
          position={[-15.702, 1.911, -14.811]}
        />
        <mesh
          name="Icosphere291"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere291.geometry}
          material={materials["Material.006"]}
          position={[-15.373, 2.904, -15.543]}
        />
        <mesh
          name="Icosphere292"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere292.geometry}
          material={materials["Material.006"]}
          position={[-15.373, 3.01, -16.725]}
        />
        <mesh
          name="Icosphere293"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere293.geometry}
          material={materials["Material.006"]}
          position={[-15.054, 3.896, -16.592]}
        />
        <mesh
          name="Icosphere294"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere294.geometry}
          material={materials["Material.006"]}
          position={[-15.054, 4.038, -15.725]}
        />
        <mesh
          name="Icosphere295"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere295.geometry}
          material={materials["Material.006"]}
          position={[-14.823, 4.998, -15.808]}
        />
        <mesh
          name="Icosphere296"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere296.geometry}
          material={materials["Material.006"]}
          position={[-14.517, 5.962, -16.076]}
        />
        <mesh
          name="Icosphere297"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere297.geometry}
          material={materials["Material.006"]}
          position={[-12.188, 2.008, -14.843]}
        />
        <mesh
          name="Icosphere298"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere298.geometry}
          material={materials["Material.006"]}
          position={[-12.183, 2.049, -16.091]}
        />
        <mesh
          name="Icosphere299"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere299.geometry}
          material={materials["Material.006"]}
          position={[-12.27, 1.911, -17.327]}
        />
        <mesh
          name="Icosphere300"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere300.geometry}
          material={materials["Material.006"]}
          position={[-12.6, 2.904, -16.595]}
        />
        <mesh
          name="Icosphere301"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere301.geometry}
          material={materials["Material.006"]}
          position={[-12.6, 3.01, -15.413]}
        />
        <mesh
          name="Icosphere302"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere302.geometry}
          material={materials["Material.006"]}
          position={[-12.919, 3.896, -15.546]}
        />
        <mesh
          name="Icosphere303"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere303.geometry}
          material={materials["Material.006"]}
          position={[-12.919, 4.038, -16.413]}
        />
        <mesh
          name="Icosphere304"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere304.geometry}
          material={materials["Material.006"]}
          position={[-13.15, 4.998, -16.33]}
        />
        <mesh
          name="Icosphere305"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere305.geometry}
          material={materials["Material.006"]}
          position={[-13.455, 5.962, -16.062]}
        />
        <mesh
          name="Icosphere306"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere306.geometry}
          material={materials["Material.006"]}
          position={[-15.213, 2.008, -14.271]}
        />
        <mesh
          name="Icosphere307"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere307.geometry}
          material={materials["Material.006"]}
          position={[-13.964, 2.049, -14.266]}
        />
        <mesh
          name="Icosphere308"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere308.geometry}
          material={materials["Material.006"]}
          position={[-12.728, 1.911, -14.353]}
        />
        <mesh
          name="Icosphere309"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere309.geometry}
          material={materials["Material.006"]}
          position={[-13.46, 2.904, -14.683]}
        />
        <mesh
          name="Icosphere310"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere310.geometry}
          material={materials["Material.006"]}
          position={[-14.642, 3.01, -14.683]}
        />
        <mesh
          name="Icosphere311"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere311.geometry}
          material={materials["Material.006"]}
          position={[-14.509, 3.896, -15.002]}
        />
        <mesh
          name="Icosphere312"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere312.geometry}
          material={materials["Material.006"]}
          position={[-13.642, 4.038, -15.002]}
        />
        <mesh
          name="Icosphere313"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere313.geometry}
          material={materials["Material.006"]}
          position={[-13.725, 4.998, -15.233]}
        />
        <mesh
          name="Icosphere314"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere314.geometry}
          material={materials["Material.006"]}
          position={[-13.993, 5.962, -15.538]}
        />
        <mesh
          name="Icosphere315"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere315.geometry}
          material={materials["Material.006"]}
          position={[-12.76, 2.008, -17.867]}
        />
        <mesh
          name="Icosphere316"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere316.geometry}
          material={materials["Material.006"]}
          position={[-14.009, 2.049, -17.873]}
        />
        <mesh
          name="Icosphere317"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere317.geometry}
          material={materials["Material.006"]}
          position={[-15.245, 1.911, -17.785]}
        />
        <mesh
          name="Icosphere318"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere318.geometry}
          material={materials["Material.006"]}
          position={[-14.513, 2.904, -17.456]}
        />
        <mesh
          name="Icosphere319"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere319.geometry}
          material={materials["Material.006"]}
          position={[-13.331, 3.01, -17.456]}
        />
        <mesh
          name="Icosphere320"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere320.geometry}
          material={materials["Material.006"]}
          position={[-13.464, 3.896, -17.136]}
        />
        <mesh
          name="Icosphere321"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere321.geometry}
          material={materials["Material.006"]}
          position={[-14.33, 4.038, -17.136]}
        />
        <mesh
          name="Icosphere322"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere322.geometry}
          material={materials["Material.006"]}
          position={[-14.247, 4.998, -16.905]}
        />
        <mesh
          name="Icosphere323"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere323.geometry}
          material={materials["Material.006"]}
          position={[-13.98, 5.962, -16.6]}
        />
        <group name="Cube1015" position={[-14, 3.833, 16]}>
          <mesh
            name="Cube1051"
            castShadow
            receiveShadow
            geometry={nodes.Cube1051.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube1051_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube1051_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          name="Icosphere324"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere324.geometry}
          material={materials["Material.006"]}
          position={[-15.784, 2.008, 14.705]}
        />
        <mesh
          name="Icosphere325"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere325.geometry}
          material={materials["Material.006"]}
          position={[-15.79, 2.049, 15.953]}
        />
        <mesh
          name="Icosphere326"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere326.geometry}
          material={materials["Material.006"]}
          position={[-15.702, 1.911, 17.189]}
        />
        <mesh
          name="Icosphere327"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere327.geometry}
          material={materials["Material.006"]}
          position={[-15.373, 2.904, 16.457]}
        />
        <mesh
          name="Icosphere328"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere328.geometry}
          material={materials["Material.006"]}
          position={[-15.373, 3.01, 15.275]}
        />
        <mesh
          name="Icosphere329"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere329.geometry}
          material={materials["Material.006"]}
          position={[-15.054, 3.896, 15.408]}
        />
        <mesh
          name="Icosphere330"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere330.geometry}
          material={materials["Material.006"]}
          position={[-15.054, 4.038, 16.275]}
        />
        <mesh
          name="Icosphere331"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere331.geometry}
          material={materials["Material.006"]}
          position={[-14.823, 4.998, 16.192]}
        />
        <mesh
          name="Icosphere332"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere332.geometry}
          material={materials["Material.006"]}
          position={[-14.517, 5.962, 15.924]}
        />
        <mesh
          name="Icosphere333"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere333.geometry}
          material={materials["Material.006"]}
          position={[-12.188, 2.008, 17.157]}
        />
        <mesh
          name="Icosphere334"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere334.geometry}
          material={materials["Material.006"]}
          position={[-12.183, 2.049, 15.909]}
        />
        <mesh
          name="Icosphere335"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere335.geometry}
          material={materials["Material.006"]}
          position={[-12.27, 1.911, 14.673]}
        />
        <mesh
          name="Icosphere336"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere336.geometry}
          material={materials["Material.006"]}
          position={[-12.6, 2.904, 15.405]}
        />
        <mesh
          name="Icosphere337"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere337.geometry}
          material={materials["Material.006"]}
          position={[-12.6, 3.01, 16.587]}
        />
        <mesh
          name="Icosphere338"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere338.geometry}
          material={materials["Material.006"]}
          position={[-12.919, 3.896, 16.454]}
        />
        <mesh
          name="Icosphere339"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere339.geometry}
          material={materials["Material.006"]}
          position={[-12.919, 4.038, 15.587]}
        />
        <mesh
          name="Icosphere340"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere340.geometry}
          material={materials["Material.006"]}
          position={[-13.15, 4.998, 15.67]}
        />
        <mesh
          name="Icosphere341"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere341.geometry}
          material={materials["Material.006"]}
          position={[-13.455, 5.962, 15.938]}
        />
        <mesh
          name="Icosphere342"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere342.geometry}
          material={materials["Material.006"]}
          position={[-15.213, 2.008, 17.729]}
        />
        <mesh
          name="Icosphere343"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere343.geometry}
          material={materials["Material.006"]}
          position={[-13.964, 2.049, 17.734]}
        />
        <mesh
          name="Icosphere344"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere344.geometry}
          material={materials["Material.006"]}
          position={[-12.728, 1.911, 17.647]}
        />
        <mesh
          name="Icosphere345"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere345.geometry}
          material={materials["Material.006"]}
          position={[-13.46, 2.904, 17.317]}
        />
        <mesh
          name="Icosphere346"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere346.geometry}
          material={materials["Material.006"]}
          position={[-14.642, 3.01, 17.317]}
        />
        <mesh
          name="Icosphere347"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere347.geometry}
          material={materials["Material.006"]}
          position={[-14.509, 3.896, 16.998]}
        />
        <mesh
          name="Icosphere348"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere348.geometry}
          material={materials["Material.006"]}
          position={[-13.642, 4.038, 16.998]}
        />
        <mesh
          name="Icosphere349"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere349.geometry}
          material={materials["Material.006"]}
          position={[-13.725, 4.998, 16.767]}
        />
        <mesh
          name="Icosphere350"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere350.geometry}
          material={materials["Material.006"]}
          position={[-13.993, 5.962, 16.462]}
        />
        <mesh
          name="Icosphere351"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere351.geometry}
          material={materials["Material.006"]}
          position={[-12.76, 2.008, 14.133]}
        />
        <mesh
          name="Icosphere352"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere352.geometry}
          material={materials["Material.006"]}
          position={[-14.009, 2.049, 14.128]}
        />
        <mesh
          name="Icosphere353"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere353.geometry}
          material={materials["Material.006"]}
          position={[-15.245, 1.911, 14.215]}
        />
        <mesh
          name="Icosphere354"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere354.geometry}
          material={materials["Material.006"]}
          position={[-14.513, 2.904, 14.544]}
        />
        <mesh
          name="Icosphere355"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere355.geometry}
          material={materials["Material.006"]}
          position={[-13.331, 3.01, 14.544]}
        />
        <mesh
          name="Icosphere356"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere356.geometry}
          material={materials["Material.006"]}
          position={[-13.464, 3.896, 14.864]}
        />
        <mesh
          name="Icosphere357"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere357.geometry}
          material={materials["Material.006"]}
          position={[-14.33, 4.038, 14.864]}
        />
        <mesh
          name="Icosphere358"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere358.geometry}
          material={materials["Material.006"]}
          position={[-14.247, 4.998, 15.095]}
        />
        <mesh
          name="Icosphere359"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere359.geometry}
          material={materials["Material.006"]}
          position={[-13.98, 5.962, 15.4]}
        />
        <group name="Cube1016" position={[14, 3.833, 16]}>
          <mesh
            name="Cube1052"
            castShadow
            receiveShadow
            geometry={nodes.Cube1052.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube1052_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube1052_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          name="Icosphere360"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere360.geometry}
          material={materials["Material.006"]}
          position={[12.216, 2.008, 14.705]}
        />
        <mesh
          name="Icosphere361"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere361.geometry}
          material={materials["Material.006"]}
          position={[12.21, 2.049, 15.953]}
        />
        <mesh
          name="Icosphere362"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere362.geometry}
          material={materials["Material.006"]}
          position={[12.298, 1.911, 17.189]}
        />
        <mesh
          name="Icosphere363"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere363.geometry}
          material={materials["Material.006"]}
          position={[12.627, 2.904, 16.457]}
        />
        <mesh
          name="Icosphere364"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere364.geometry}
          material={materials["Material.006"]}
          position={[12.627, 3.01, 15.275]}
        />
        <mesh
          name="Icosphere365"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere365.geometry}
          material={materials["Material.006"]}
          position={[12.946, 3.896, 15.408]}
        />
        <mesh
          name="Icosphere366"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere366.geometry}
          material={materials["Material.006"]}
          position={[12.946, 4.038, 16.275]}
        />
        <mesh
          name="Icosphere367"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere367.geometry}
          material={materials["Material.006"]}
          position={[13.177, 4.998, 16.192]}
        />
        <mesh
          name="Icosphere368"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere368.geometry}
          material={materials["Material.006"]}
          position={[13.483, 5.962, 15.924]}
        />
        <mesh
          name="Icosphere369"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere369.geometry}
          material={materials["Material.006"]}
          position={[15.812, 2.008, 17.157]}
        />
        <mesh
          name="Icosphere370"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere370.geometry}
          material={materials["Material.006"]}
          position={[15.817, 2.049, 15.909]}
        />
        <mesh
          name="Icosphere371"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere371.geometry}
          material={materials["Material.006"]}
          position={[15.73, 1.911, 14.673]}
        />
        <mesh
          name="Icosphere372"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere372.geometry}
          material={materials["Material.006"]}
          position={[15.4, 2.904, 15.405]}
        />
        <mesh
          name="Icosphere373"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere373.geometry}
          material={materials["Material.006"]}
          position={[15.4, 3.01, 16.587]}
        />
        <mesh
          name="Icosphere374"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere374.geometry}
          material={materials["Material.006"]}
          position={[15.081, 3.896, 16.454]}
        />
        <mesh
          name="Icosphere375"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere375.geometry}
          material={materials["Material.006"]}
          position={[15.081, 4.038, 15.587]}
        />
        <mesh
          name="Icosphere376"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere376.geometry}
          material={materials["Material.006"]}
          position={[14.85, 4.998, 15.67]}
        />
        <mesh
          name="Icosphere377"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere377.geometry}
          material={materials["Material.006"]}
          position={[14.545, 5.962, 15.938]}
        />
        <mesh
          name="Icosphere378"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere378.geometry}
          material={materials["Material.006"]}
          position={[12.787, 2.008, 17.729]}
        />
        <mesh
          name="Icosphere379"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere379.geometry}
          material={materials["Material.006"]}
          position={[14.036, 2.049, 17.734]}
        />
        <mesh
          name="Icosphere380"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere380.geometry}
          material={materials["Material.006"]}
          position={[15.272, 1.911, 17.647]}
        />
        <mesh
          name="Icosphere381"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere381.geometry}
          material={materials["Material.006"]}
          position={[14.54, 2.904, 17.317]}
        />
        <mesh
          name="Icosphere382"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere382.geometry}
          material={materials["Material.006"]}
          position={[13.358, 3.01, 17.317]}
        />
        <mesh
          name="Icosphere383"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere383.geometry}
          material={materials["Material.006"]}
          position={[13.491, 3.896, 16.998]}
        />
        <mesh
          name="Icosphere384"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere384.geometry}
          material={materials["Material.006"]}
          position={[14.358, 4.038, 16.998]}
        />
        <mesh
          name="Icosphere385"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere385.geometry}
          material={materials["Material.006"]}
          position={[14.275, 4.998, 16.767]}
        />
        <mesh
          name="Icosphere386"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere386.geometry}
          material={materials["Material.006"]}
          position={[14.007, 5.962, 16.462]}
        />
        <mesh
          name="Icosphere387"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere387.geometry}
          material={materials["Material.006"]}
          position={[15.24, 2.008, 14.133]}
        />
        <mesh
          name="Icosphere388"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere388.geometry}
          material={materials["Material.006"]}
          position={[13.991, 2.049, 14.128]}
        />
        <mesh
          name="Icosphere389"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere389.geometry}
          material={materials["Material.006"]}
          position={[12.755, 1.911, 14.215]}
        />
        <mesh
          name="Icosphere390"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere390.geometry}
          material={materials["Material.006"]}
          position={[13.487, 2.904, 14.544]}
        />
        <mesh
          name="Icosphere391"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere391.geometry}
          material={materials["Material.006"]}
          position={[14.669, 3.01, 14.544]}
        />
        <mesh
          name="Icosphere392"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere392.geometry}
          material={materials["Material.006"]}
          position={[14.536, 3.896, 14.864]}
        />
        <mesh
          name="Icosphere393"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere393.geometry}
          material={materials["Material.006"]}
          position={[13.67, 4.038, 14.864]}
        />
        <mesh
          name="Icosphere394"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere394.geometry}
          material={materials["Material.006"]}
          position={[13.753, 4.998, 15.095]}
        />
        <mesh
          name="Icosphere395"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere395.geometry}
          material={materials["Material.006"]}
          position={[14.02, 5.962, 15.4]}
        />
        <group name="Cube1032" position={[-14, 3.833, -16]}>
          <mesh
            name="Cube608"
            castShadow
            receiveShadow
            geometry={nodes.Cube608.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube608_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube608_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <group name="Cube008" position={[14, 3.833, -16]}>
          <mesh
            name="Cube700"
            castShadow
            receiveShadow
            geometry={nodes.Cube700.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube700_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube700_1.geometry}
            material={materials["Material.005"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/trees.glb");
